baseURL = 'http://darkawesome.github.io/blog'
languageCode = 'en-us'
theme = "hugo-coder"
title = "DarkAwesome"

[markup.highlight]
style = "github-dark"

[params]
	commentoURL = "https://cdn.commento.io"  # Replace if you use a custom domain 
	author = "DarkAwesome"
	info = "Backend Engineer | System Administrator | Data Analyst "
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5
	avatarurl = "https://avatars.githubusercontent.com/u/38367397?v=4"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/darkawesome/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/haveibeenpwned"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://darkawesome.github.io/blog/index.xml"
rel = "alternate"
type = "application/rss+xml"

# Menu links
[menu]
 [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-heart'></i>"
    url = "/contact/"
    weight = -100
  
  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-heart'></i>"
    url = "/blog/resume"
    weight = -95

  [[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/blog/"